<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>AlternativeDataDriveDemo</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>7</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>4814d933-e5b4-4632-b48e-ca1a65938faa</testSuiteGuid>
   <testCaseLink>
      <guid>1e03c105-50c7-4a5a-b137-44fd64a3dd7e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Demo Test/DataDrivenDemo</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>b7b08b38-e3f9-46ad-946d-0f410730de94</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value>1-2</value>
         </iterationEntity>
         <testDataId>Data Files/LoginData</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>b7b08b38-e3f9-46ad-946d-0f410730de94</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>c0832155-19b3-4e4b-a2b0-27aebd033b31</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>b7b08b38-e3f9-46ad-946d-0f410730de94</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>b34d4140-1fd5-4a9a-a794-6a53de63a8b5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>905633b8-ad68-47fb-8119-d844e1cef9c5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Demo Test/DataDrivenDemo</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>38156a6e-fc22-47ff-b327-e95038e3194b</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/LoginData</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c0832155-19b3-4e4b-a2b0-27aebd033b31</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b34d4140-1fd5-4a9a-a794-6a53de63a8b5</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
