<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_form</name>
   <tag></tag>
   <elementGuidId>8179c972-cd1b-4989-ad1b-d5fa2b4248e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'form')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(40) > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1c1c9afc-83ad-45ac-8add-f49bf31da89f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/html/tags/html_form_tag.cfm</value>
      <webElementGuid>5a375314-4f50-4ada-9c57-1d73a90a70a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>c50976c5-ba74-43d6-ba6a-df293a4adcbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;main&quot;]/article[@class=&quot;content&quot;]/div[@class=&quot;index&quot;]/div[@class=&quot;cell&quot;]/ul[@class=&quot;col-3 taglist&quot;]/li[40]/a[1]</value>
      <webElementGuid>721bbc0d-f475-4709-814f-c15830fd51bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'form')]</value>
      <webElementGuid>a2d4fb29-7e32-4b8f-8763-1aacd984b10d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='footer'])[1]/following::a[1]</value>
      <webElementGuid>10a9750a-0827-4036-a428-e9dad33ffa51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='figure'])[1]/following::a[2]</value>
      <webElementGuid>61918206-115c-4cb0-9132-7456a3c236de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='h1'])[1]/preceding::a[1]</value>
      <webElementGuid>1d2c3fdc-fb75-4e25-a1e6-d8b03ab80da3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='h2'])[1]/preceding::a[2]</value>
      <webElementGuid>ec587ece-9414-48da-8960-9c513e6d4860</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='form']/parent::*</value>
      <webElementGuid>00a0bba3-a54c-44a7-8e44-7197dbb7bda7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/html/tags/html_form_tag.cfm')]</value>
      <webElementGuid>4027e244-06d0-47cd-b8c0-aea3972f7c27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[40]/a</value>
      <webElementGuid>bf36502a-8338-4502-bcaf-ea351f1e2b6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/html/tags/html_form_tag.cfm' and (text() = 'form' or . = 'form')]</value>
      <webElementGuid>d29011ab-fc2a-4a94-a48e-1e9963019a91</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
