<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>font_Message Book</name>
   <tag></tag>
   <elementGuidId>240a5931-16c5-4e1a-93f8-99918a2c4f3c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter your name:'])[1]/preceding::font[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>font</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>font</value>
      <webElementGuid>c6534996-948a-4fd7-961b-a660ea4f9eee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>+2</value>
      <webElementGuid>3d596c1c-8f70-4d64-b101-df0d2d00a483</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>color</name>
      <type>Main</type>
      <value>WHITE</value>
      <webElementGuid>a755c474-d4c4-452b-8fc3-7a8dc3597392</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Message Book</value>
      <webElementGuid>14270bf6-d479-4596-832f-179652ffb151</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/table[1]/tbody[1]/tr[1]/td[1]/div[1]/b[1]/font[1]</value>
      <webElementGuid>3a70fd8a-5975-4e32-919a-164037827a2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_A Page with 3 Frames/frame_1</value>
      <webElementGuid>25de5fb3-cc9a-461f-b155-24789b2304ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter your name:'])[1]/preceding::font[1]</value>
      <webElementGuid>3a15a3e7-bc20-4bc1-9844-ad44dcf24d76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Browser and versions:'])[1]/preceding::font[2]</value>
      <webElementGuid>b72a5c4b-490a-44f2-b1ac-c4f2d4706ab8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Message Book']/parent::*</value>
      <webElementGuid>1243a119-c93b-46bf-a8fc-13e56b0b2375</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//font</value>
      <webElementGuid>cb6704ac-9303-42ac-a644-a7ed166926fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//font[(text() = ' Message Book' or . = ' Message Book')]</value>
      <webElementGuid>14d7eb59-14ff-4c8e-a42e-f46eadab621a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
