<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>frame</name>
   <tag></tag>
   <elementGuidId>c8505161-125c-4e74-bec2-15dd413b55e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//frame</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>frame</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>frame</value>
      <webElementGuid>1d5ac910-d52e-4624-8bd1-1c53ae795d40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>htmlf.htm</value>
      <webElementGuid>4894639e-9bb1-47b9-a18b-c3a52a8f632c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/frameset[1]/frame[1]</value>
      <webElementGuid>e46e51ec-17be-4dc4-87c0-f82e710741e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//frame</value>
      <webElementGuid>2bcfcbac-f876-4899-9b6f-552a2da37f27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//frame[@src = 'htmlf.htm']</value>
      <webElementGuid>fba6ba71-6a1b-4fa9-a4c5-8861201a6dde</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
