<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>frame_1_2</name>
   <tag></tag>
   <elementGuidId>d53f6595-6a66-4ee6-ac83-c93aef71ee2d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//frame[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>frame:nth-of-type(3)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>frame</value>
      <webElementGuid>48afb946-7e2a-4001-8890-e4712935f4a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>tags.htm</value>
      <webElementGuid>0e729f36-006e-43f5-b491-7d3d1bbb121e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/frameset[1]/frame[3]</value>
      <webElementGuid>3f64a9f4-94a4-438e-94ab-2904a6b04a75</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//frame[3]</value>
      <webElementGuid>052e728b-b0ff-47ab-a54c-d84b605cdf1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//frame[@src = 'tags.htm']</value>
      <webElementGuid>7b890308-1abb-4318-90ed-0ffed1dcf0a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
