<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Contents</name>
   <tag></tag>
   <elementGuidId>8803be54-85d3-45d7-9ede-6abed72c97ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Background'])[1]/preceding::p[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>f597b574-b1ca-4bf1-8d66-a2dbcf5ba61d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>title</value>
      <webElementGuid>f7210c2f-993e-4f09-9ab0-6e2ab7c088cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Contents </value>
      <webElementGuid>295034bd-8c0e-4e45-8742-f8e0b48d98fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/p[@class=&quot;title&quot;]</value>
      <webElementGuid>cd670e64-259d-47d1-8dea-ae294ce048b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_A Page with 3 Frames/frame</value>
      <webElementGuid>fc5bec9d-7f17-4bb3-b49a-d8ef3283aa84</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Background'])[1]/preceding::p[1]</value>
      <webElementGuid>224f39dc-de4d-49fa-a20b-7671611cb854</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Contents']/parent::*</value>
      <webElementGuid>01e632db-ead2-4aef-9452-b8d909bb4c9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[2]</value>
      <webElementGuid>6b6ad70c-6c40-49ad-a2db-a7f9aa99b8e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Contents ' or . = 'Contents ')]</value>
      <webElementGuid>8f69f5c7-0d5e-40ce-83d1-ca07b0948437</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
