<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>font_Message Book</name>
   <tag></tag>
   <elementGuidId>0b398733-2d28-475d-a9cf-308f8941f1d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter your name:'])[1]/preceding::font[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>font</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>font</value>
      <webElementGuid>6d085c5e-1169-4255-86a3-7271fd21a48c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>+2</value>
      <webElementGuid>1022191e-810b-4e22-b1e0-6e09bed7da74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>color</name>
      <type>Main</type>
      <value>WHITE</value>
      <webElementGuid>360640e1-4d12-4d52-860a-db3019e54715</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Message Book</value>
      <webElementGuid>74abb1a2-c4da-4d4c-b9c2-49a097e99362</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/table[1]/tbody[1]/tr[1]/td[1]/div[1]/b[1]/font[1]</value>
      <webElementGuid>653463ff-e30d-4177-abf4-659d49d29871</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/FramesSample/Page_A Page with 3 Frames/frame_1</value>
      <webElementGuid>cdb1f158-c27a-45ef-8060-78d1bddadce0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter your name:'])[1]/preceding::font[1]</value>
      <webElementGuid>bac7011b-69e7-4853-869c-893780cb9e2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Browser and versions:'])[1]/preceding::font[2]</value>
      <webElementGuid>bd9b5965-401e-4b1d-a441-c0c0c9486149</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Message Book']/parent::*</value>
      <webElementGuid>7e219ff6-e855-4ee1-87d4-94279d5902e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//font</value>
      <webElementGuid>c443644b-0810-4c71-a2c4-6ea3ea8a5648</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//font[(text() = ' Message Book' or . = ' Message Book')]</value>
      <webElementGuid>a514c6b5-1673-4fb5-aeb9-9e37610d6473</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
