<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>frame</name>
   <tag></tag>
   <elementGuidId>1b0a7755-a20f-48db-8f5b-0d5113ffa205</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//frame</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>frame</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>frame</value>
      <webElementGuid>2979b577-d65f-4fe6-a737-9966e8adeadb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>htmlf.htm</value>
      <webElementGuid>364c63f8-7bf0-42e4-98d1-45a1be7cc6c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/frameset[1]/frame[1]</value>
      <webElementGuid>194a7128-cdd9-448f-bfec-dcc060dd1001</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//frame</value>
      <webElementGuid>6e65c08b-b3ac-4f75-b853-05ad33699e56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//frame[@src = 'htmlf.htm']</value>
      <webElementGuid>76ac3ad6-cda0-414f-a4b5-db1e7ad3a696</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
